name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Apply)
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform plan -var="client_id=${{ secrets.ARM_CLIENT_ID }}" -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" -var="location=East US" -var="rg_name=my-resource-group"

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -auto-approve -var="client_id=${{ secrets.ARM_CLIENT_ID }}" -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" -var="location=East US" -var="rg_name=my-resource-group"

      - name: Terraform Plan (Destroy)
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform plan -destroy -var="client_id=${{ secrets.ARM_CLIENT_ID }}" -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" -var="location=East US" -var="rg_name=my-resource-group"

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve -var="client_id=${{ secrets.ARM_CLIENT_ID }}" -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" -var="location=East US" -var="rg_name=my-resource-group"
