name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan \
          -var="client_id=${{ secrets.ARM_CLIENT_ID }}" \
          -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
          -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
          -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
          -var="location=East US" \
          -var="rg_name=my-resource-group"

      - name: Terraform Apply or Destroy
        run: |
          if [ "${{ github.event.inputs.action }}" = "apply" ]; then
            echo "Running Terraform Apply"
            terraform apply -auto-approve \
              -var="client_id=${{ secrets.ARM_CLIENT_ID }}" \
              -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
              -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
              -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
              -var="location=East US" \
              -var="rg_name=my-resource-group"
          elif [ "${{ github.event.inputs.action }}" = "destroy" ]; then
            echo "Running Terraform Destroy"
            terraform destroy -auto-approve \
              -var="client_id=${{ secrets.ARM_CLIENT_ID }}" \
              -var="client_secret=${{ secrets.ARM_CLIENT_SECRET }}" \
              -var="subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" \
              -var="tenant_id=${{ secrets.ARM_TENANT_ID }}" \
              -var="location=East US" \
              -var="rg_name=my-resource-group"
          else
            echo "Invalid action: ${{ github.event.inputs.action }}"
            exit 1
